---
- name: Configure managed nodes
  hosts: managed
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Configure virtual host
      copy:
        content: |
          server {
              listen 80;
              root /var/www/html;
              index index.html;
          }
        dest: /etc/nginx/sites-enabled/default

    - name: Create index.html
      copy:
        content: "<h1>Hello from Ansible</h1>"
        dest: /var/www/html/index.html

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted